openapi: 3.2.0
info:
  title: APImetrics Inventory API
  description: API for the APImetrics platform
  termsOfService: http://apimetrics.io/tos/
  contact:
    name: APIContext Support
    url: https://apicontext.io/
    email: support@apicontext.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: v2026-09-02
tags:
- name: Inventory
paths:
  /api/3/inventory:
    get:
      tags:
      - Inventory
      summary: List-Inventory
      description: Return a list of discovered endpoints.
      operationId: list-inventory
      security:
      - OAuth2: []
      - ApiKey: []
      parameters:
      - name: from_timestamp
        in: query
        required: true
        schema:
          type: string
          format: date-time
          title: From Timestamp
      - name: to_timestamp
        in: query
        required: true
        schema:
          type: string
          format: date-time
          title: To Timestamp
      - name: cursor
        in: query
        required: false
        schema:
          type: integer
          default: 0
          title: Cursor
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 25
          title: Limit
      - name: apimetrics-project-id
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Apimetrics-Project-Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response List-Inventory
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/3/inventory/coverage:
    get:
      tags:
      - Inventory
      summary: Oas-Coverage
      description: Return API call coverage data for OpenAPI endpoints.
      operationId: oas-coverage
      security:
      - OAuth2: []
      - ApiKey: []
      parameters:
      - name: from_timestamp
        in: query
        required: true
        schema:
          type: string
          format: date-time
          title: From Timestamp
      - name: to_timestamp
        in: query
        required: true
        schema:
          type: string
          format: date-time
          title: To Timestamp
      - name: apimetrics-project-id
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Apimetrics-Project-Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Oas-Coverage
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/3/inventory/endpoints/{file_id}:
    get:
      tags:
      - Inventory
      summary: Oas-Endpoints
      description: Return a list of endpoints for the requested OpenAPI spec.
      operationId: oas-endpoints
      security:
      - OAuth2: []
      - ApiKey: []
      parameters:
      - name: file_id
        in: path
        required: true
        schema:
          type: string
          title: File Id
      - name: apimetrics-project-id
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Apimetrics-Project-Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Oas-Endpoints
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            openid: OpenID Connect identity
            profile: User profile
            email: User email address
          authorizationUrl: https://auth.apimetrics.io/authorize?audience=https://client.apimetrics.io
          tokenUrl: https://auth.apimetrics.io/oauth/token
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
